#!/bin/bash
#SBATCH -J LULU
#SBATCH -o out_err_files/LULU_%A.out
#SBATCH -e out_err_files/LULU_%A.err
#SBATCH --nodes=1
#SBATCH -t 5-00:00:00
#SBATCH -p defq
#SBATCH --mail-type=ALL
#SBATCH --mail-user=bnguyen@gwu.edu

module load R/3.5.3

cut -f1,2,3,5,6,7,8,9 --complement swarm_13.otutable >swarm_13_trim.otutable #remove extra fields generated by OTU_table script
# Takes ~1.5 days
# generate curated OTU table
Rscript LULU_swarm.R
